name: figma_make_app
description: Smart Attendance System rewritten in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.8.0
  csv: ^6.0.0
  file_selector: ^1.0.3
  firebase_auth: ^6.5.7
  firebase_core: ^4.13.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.4
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
