// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfDG6u8S5Vgl06rlXPT9d2P8qG4FXBJHk',
    appId: '1:677194023410:web:34b62d774a2fe1b92cab6b',
    messagingSenderId: '677194023410',
    projectId: 'smart-attendance-ba64a',
    authDomain: 'smart-attendance-ba64a.firebaseapp.com',
    storageBucket: 'smart-attendance-ba64a.firebasestorage.app',
    measurementId: 'G-SPJDD0XBWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD-j6NI_tH85CrjKStIQZN05V4UARXhKs',
    appId: '1:677194023410:android:47d181f206bf214c2cab6b',
    messagingSenderId: '677194023410',
    projectId: 'smart-attendance-ba64a',
    storageBucket: 'smart-attendance-ba64a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEYq6zMP2rOcmzH8BR8T2o-QUx8GA81J4',
    appId: '1:677194023410:ios:678f7b24b3dd90d12cab6b',
    messagingSenderId: '677194023410',
    projectId: 'smart-attendance-ba64a',
    storageBucket: 'smart-attendance-ba64a.firebasestorage.app',
    iosClientId: '677194023410-tv58ogpd6halq3fm1r8nq7islvoi5739.apps.googleusercontent.com',
    iosBundleId: 'com.example.figmaMakeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEYq6zMP2rOcmzH8BR8T2o-QUx8GA81J4',
    appId: '1:677194023410:ios:678f7b24b3dd90d12cab6b',
    messagingSenderId: '677194023410',
    projectId: 'smart-attendance-ba64a',
    storageBucket: 'smart-attendance-ba64a.firebasestorage.app',
    iosClientId: '677194023410-tv58ogpd6halq3fm1r8nq7islvoi5739.apps.googleusercontent.com',
    iosBundleId: 'com.example.figmaMakeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfDG6u8S5Vgl06rlXPT9d2P8qG4FXBJHk',
    appId: '1:677194023410:web:321dd7bbd0f03f162cab6b',
    messagingSenderId: '677194023410',
    projectId: 'smart-attendance-ba64a',
    authDomain: 'smart-attendance-ba64a.firebaseapp.com',
    storageBucket: 'smart-attendance-ba64a.firebasestorage.app',
    measurementId: 'G-GRK3RJ7BY7',
  );
}
